import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { BsSunFill } from "react-icons/bs";
import Hero from "./components/Hero";
import Services from "./components/Services";
import Portfolio from "./components/Portfolio";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  <BsFillMoonStarsFill
    className="cursor-pointer text-2xl"
    onClick={() => setDarkMode(!darkMode)}
  />;
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Samuel Pokam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 pb-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section>
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-slate-100">
              devbyRinKhimera
            </h1>
            <ul className="flex items-center">
              <li>
                {darkMode === false && (
                  <BsFillMoonStarsFill
                    className="cursor-pointer text-2xl"
                    onClick={() => setDarkMode(!darkMode)}
                  />
                )}
                {darkMode === true && (
                  <BsSunFill
                    className="cursor-pointer text-2xl text-slate-100"
                    onClick={() => setDarkMode(!darkMode)}
                  />
                )}
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-lg ml-8 "
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <Hero />
        </section>
        <Services />
        <Portfolio />
      </main>
    </div>
  );
}
